name: Maven Publish

# 检测到 src 文件内 .java 文件有变动执行编译
on:
  push:
    tags:
      - '*'

jobs:
  build:
    #	配置权限
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      # 下载代码
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        # 安装 JDK
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven
      # 配置 settings.xml 一般用于 Maven 私库验证等
      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@v20
        with:
          repositories: ''
          servers: ''
      # Maven 打包
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      # 将打包好的 Jar 包 放到 staging 文件夹
      - name: Copy files
        run: mkdir staging && cp target/libs/*.jar staging && cp target/libs/*.sha1 staging
      # 设置 jobs Maven pom 版本环境变量
      - name: Setup Environments
        run: |
          echo "RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
      # 上传文件并发布 Release- name: Release Upload
      - name: Publish to GitHub Releases
        # You may pin to the exact commit or the version.
        # uses: d1ceward/draft-assets-release-action@f2997b18bb04e00260f1d67c796b04a56ca6ea2e
        uses: d1ceward/draft-assets-release-action@v2.0.0
        with:
          # The GitHub access token which will be used to upload release artifacts.
          token: "${{ secrets.GITHUB_TOKEN }}"
          # A list of files to publish, relative to the repository root.
          files: |
            staging/*.jar
            staging/*.sha1
      - name: Branch Creator
        uses: Vent-Finance/branch_creator@v1.0.0
        with:
          name: "${{ env.RELEASE_VERSION }}"
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
